[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile && npx prisma@5.22.0 generate --schema=./packages/database/prisma/schema.prisma && pnpm -C packages/database build && pnpm -C apps/api build
"

[deploy]
startCommand = "cd apps/api && pnpm start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.env]
NODE_ENV = "production"
