[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile"

[deploy]
startCommand = "/bin/bash -c 'cd apps/api && pnpm start:prod'"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.env]
NODE_ENV = "production"
SHELL = "/bin/bash"
