[build]
builder = "nixpacks"
buildCommand = "/bin/bash -c 'pnpm install --no-frozen-lockfile && npx prisma@5.22.0 generate --schema=./packages/database/prisma/schema.prisma && pnpm -C packages/database build && pnpm -C apps/api build'"

[deploy]
startCommand = "/bin/bash -c 'cd apps/api && pnpm start:prod'"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.env]
NODE_ENV = "production"
SHELL = "/bin/bash"
